# the docker-compose.yml file is used by AWS EBS to pull image from docker hub,
# only images of container 3), 4), 5), 6) are pulled while the application is 
# deploying to EBS env. the postgress and redis containers are not built, instead, 
# using RDS and ElastiCache services.

# 3) proxy 
# 4) api-Server
# 5) worker
# 6) client ( the web server )


version: '3.8'

services:

  proxy:
    image: jefftimes/mca-proxy:prod
    mem_limit: 128m
    hostname: proxy
    depends_on:
      - client
      - api-server
    ports: 
      - 80:80
  
  api-server:
    image: jefftimes/mca-api-server:prod 
    mem_limit: 128m
    hostname: api-server
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT 
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
    ports:
      - 5500:5500
  
  worker:
    image: jefftimes/mca-worker:prod
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    
  client:
    image: jefftimes/mca-client:prod
    mem_limit: 128m
    hostname: client
    ports:
      - 3000:3000
    