version: '3.8'

services:
  
  postgres:
    image: postgres:14-alpine
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=apiserver
      - POSTGRES_DB=fib_indices
    ports:
      - 5432:5432
  
  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

  nginx:
    restart: always
    depends_on:
      - client
      - api-server
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - 80:80
  
  api-server:
    build: 
      dockerfile: Dockerfile
      context: ./api-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=fib_indices
      - PGUSER=apiserver
      - PGPASSWORD=password
    ports:
      - 5500:5500
  
  worker:
    build: 
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - 3000:3000
    